### Data Preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('train.csv')
df_test=pd.read_csv('test.csv')
df.head(2)

,video_id,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,likes
0,53364,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,2351.0
1,51040,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,3264.0

In [3]:
df_test.head(2)

,video_id,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code
0,87185,జనవరి 31 గ్రహణం రోజు కొడుకులు ఉన్నవాళ్లు ఏం చే...,CHIRRAVURI FOUNDATION,22.0,2018-01-17,"Chirravuri|""Foundation""|""chirravuri foundation...",80793.0,54.0,79.0,8885569579...CHIRRAVURI FOUNDATION.\n\n☛Subsct...,IN
1,9431,ठाणे:'जेव्हा सत्ता बदलेल तेव्हा केस तुमच्यावरह...,VIRAL IN INDIA,22.0,2017-11-18,"Raj Thackeray|""LIVE SPEECH""|""latest Speech""|""r...",150317.0,230.0,311.0,Don't Forget to SUBSCIRBE to our YouTube Chann...,IN

In [4]:
print(df.shape,df_test.shape)

(26061, 12) (11170, 11)

In [5]:
tot_df=pd.concat([df,df_test]).reset_index()
print(tot_df.shape)
tot_df.head(2)

(37231, 13)

,index,video_id,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,likes
0,0,53364,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,2351.0
1,1,51040,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,3264.0

In [6]:
tot_df.drop(labels=['index','video_id'],axis=1,inplace=True)
tot_df.head(2)

,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,likes
0,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,2351.0
1,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,3264.0

In [8]:
tot_df['likes'].fillna(value=-999,inplace=True)
tot_df['likes'].isnull().sum()

0

In [11]:
tot_df['category_id'].value_counts()

24.0    13719
25.0     5241
22.0     3360
10.0     2990
23.0     2459
17.0     2050
26.0     1858
1.0      1446
27.0     1426
28.0      921
20.0      790
2.0       312
15.0      262
19.0      207
29.0      123
43.0       66
30.0        1
Name: category_id, dtype: int64

In [17]:
category_id_dict=dict(tot_df[tot_df['likes']!=-999].groupby('category_id')['likes'].median())
category_id_dict

{1.0: 3179.0,
 2.0: 8620.0,
 10.0: 10392.0,
 15.0: 7570.0,
 17.0: 1901.0,
 19.0: 5432.0,
 20.0: 9078.5,
 22.0: 1927.0,
 23.0: 8191.5,
 24.0: 1817.0,
 25.0: 949.0,
 26.0: 5421.0,
 27.0: 2969.5,
 28.0: 10669.0,
 29.0: 1050.0,
 30.0: 1497.0,
 43.0: 2967.0}

In [22]:
tot_df['category_id_median_likes']=tot_df['category_id'].replace(category_id_dict)
tot_df.head(2)

,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,likes,category_id_median_likes
0,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,2351.0,1817.0
1,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,3264.0,1817.0

In [26]:
chk=pd.get_dummies(tot_df['country_code'],drop_first=True)
tot_df=pd.concat([tot_df,chk],axis=1)
tot_df.head(2)

,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,likes,category_id_median_likes,GB,IN,US
0,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,2351.0,1817.0,0,0,0
1,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,3264.0,1817.0,0,0,0

In [29]:
tot_df['publish_date']=pd.to_datetime(tot_df['publish_date'],format='%Y-%m-%d')
tot_df['publish_year']=tot_df['publish_date'].dt.year
tot_df['publish_month']=tot_df['publish_date'].dt.month
tot_df['publish_day']=tot_df['publish_date'].dt.day
tot_df.head(2)

,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,likes,category_id_median_likes,GB,IN,US,publish_year,publish_month,publish_day
0,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,2351.0,1817.0,0,0,0,2017,12,12
1,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,3264.0,1817.0,0,0,0,2018,3,8

In [37]:
from sklearn.preprocessing import StandardScaler
views_std=StandardScaler()
views_std.fit(tot_df[tot_df['likes']!=-999][['views']])
values=views_std.transform(tot_df[['views']])
tot_df=pd.concat([tot_df,pd.DataFrame(values,columns=['views_std'])],axis=1)
tot_df.head(2)

,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,likes,category_id_median_likes,GB,IN,US,publish_year,publish_month,publish_day,views_std
0,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,2351.0,1817.0,0,0,0,2017,12,12,-0.022662
1,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,3264.0,1817.0,0,0,0,2018,3,8,0.046318

In [38]:
dislikes_std=StandardScaler()
dislikes_std.fit(tot_df[tot_df['likes']!=-999][['dislikes']])
values=dislikes_std.transform(tot_df[['dislikes']])
tot_df=pd.concat([tot_df,pd.DataFrame(values,columns=['dislikes_std'])],axis=1)
tot_df.head(2)

,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,likes,category_id_median_likes,GB,IN,US,publish_year,publish_month,publish_day,views_std,dislikes_std
0,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,2351.0,1817.0,0,0,0,2017,12,12,-0.022662,-0.077389
1,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,3264.0,1817.0,0,0,0,2018,3,8,0.046318,-0.149251

In [39]:
comments_std=StandardScaler()
comments_std.fit(tot_df[tot_df['likes']!=-999][['comment_count']])
values=comments_std.transform(tot_df[['comment_count']])
tot_df=pd.concat([tot_df,pd.DataFrame(values,columns=['comment_count_std'])],axis=1)
tot_df.head(2)

,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,...,category_id_median_likes,GB,IN,US,publish_year,publish_month,publish_day,views_std,dislikes_std,comment_count_std
0,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,...,1817.0,0,0,0,2017,12,12,-0.022662,-0.077389,-0.085769
1,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,...,1817.0,0,0,0,2018,3,8,0.046318,-0.149251,-0.149138

In [40]:
category_id_median_likes_std=StandardScaler()
category_id_median_likes_std.fit(tot_df[tot_df['likes']!=-999][['category_id_median_likes']])
values=category_id_median_likes_std.transform(tot_df[['category_id_median_likes']])
tot_df=pd.concat([tot_df,pd.DataFrame(values,columns=['category_id_median_likes_std'])],axis=1)
tot_df.head(2)

,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,...,GB,IN,US,publish_year,publish_month,publish_day,views_std,dislikes_std,comment_count_std,category_id_median_likes_std
0,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,...,0,0,0,2017,12,12,-0.022662,-0.077389,-0.085769,-0.55453
1,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,...,0,0,0,2018,3,8,0.046318,-0.149251,-0.149138,-0.55453

In [41]:
publish_year_std=StandardScaler()
publish_year_std.fit(tot_df[tot_df['likes']!=-999][['publish_year']])
values=publish_year_std.transform(tot_df[['publish_year']])
tot_df=pd.concat([tot_df,pd.DataFrame(values,columns=['publish_year_std'])],axis=1)

publish_month_std=StandardScaler()
publish_month_std.fit(tot_df[tot_df['likes']!=-999][['publish_month']])
values=publish_month_std.transform(tot_df[['publish_month']])
tot_df=pd.concat([tot_df,pd.DataFrame(values,columns=['publish_month_std'])],axis=1)

publish_day_std=StandardScaler()
publish_day_std.fit(tot_df[tot_df['likes']!=-999][['publish_day']])
values=publish_day_std.transform(tot_df[['publish_day']])
tot_df=pd.concat([tot_df,pd.DataFrame(values,columns=['publish_day_std'])],axis=1)

tot_df.head(2)

,title,channel_title,category_id,publish_date,tags,views,dislikes,comment_count,description,country_code,...,publish_year,publish_month,publish_day,views_std,dislikes_std,comment_count_std,category_id_median_likes_std,publish_year_std,publish_month_std,publish_day_std
0,Alif Allah Aur Insaan Episode 34 HUM TV Drama ...,HUM TV,24.0,2017-12-12,"HUM|""TV""|""Alif Allah Aur Insaan""|""Episode 34""|...",351430.0,298.0,900.0,Alif Allah Aur Insaan Episode 34 Full - 12 Dec...,CA,...,2017,12,12,-0.022662,-0.077389,-0.085769,-0.55453,-1.274060,1.630641,-0.425818
1,It's Showtime Miss Q & A: Bela gets jealous of...,ABS-CBN Entertainment,24.0,2018-03-08,"ABS-CBN Entertainment|""ABS-CBN""|""ABS-CBN Onlin...",461508.0,74.0,314.0,Vice Ganda notices Bela Padilla's sudden chang...,CA,...,2018,3,8,0.046318,-0.149251,-0.149138,-0.55453,0.524406,-0.591444,-0.885316

In [42]:
tot_df.columns

Index(['title', 'channel_title', 'category_id', 'publish_date', 'tags',
       'views', 'dislikes', 'comment_count', 'description', 'country_code',
       'likes', 'category_id_median_likes', 'GB', 'IN', 'US', 'publish_year',
       'publish_month', 'publish_day', 'views_std', 'dislikes_std',
       'comment_count_std', 'category_id_median_likes_std', 'publish_year_std',
       'publish_month_std', 'publish_day_std'],
      dtype='object')

In [46]:
final_df=tot_df.drop(labels=['title','channel_title','category_id','publish_date','tags','views','dislikes','comment_count','description','country_code','category_id_median_likes','publish_year','publish_month','publish_day'],axis=1)
final_df.head(2)

,likes,GB,IN,US,views_std,dislikes_std,comment_count_std,category_id_median_likes_std,publish_year_std,publish_month_std,publish_day_std
0,2351.0,0,0,0,-0.022662,-0.077389,-0.085769,-0.55453,-1.274060,1.630641,-0.425818
1,3264.0,0,0,0,0.046318,-0.149251,-0.149138,-0.55453,0.524406,-0.591444,-0.885316

In [50]:
final_df.to_csv('final_df_without_text.csv',index=False)
tot_df.to_csv('tot_df.csv',index=False)

In [52]:
test=final_df[final_df['likes']==-999]
test.head()

,likes,GB,IN,US,views_std,dislikes_std,comment_count_std,category_id_median_likes_std,publish_year_std,publish_month_std,publish_day_std
26061,-999.0,0,1,0,-0.192257,-0.155667,-0.174551,-0.519940,0.524406,-1.085240,0.148555
26062,-999.0,0,1,0,-0.148690,-0.099205,-0.149463,-0.519940,-1.274060,1.383742,0.263430
26063,-999.0,0,0,0,-0.238776,-0.169783,-0.182337,-0.528116,-1.274060,1.630641,-1.689438
26064,-999.0,0,0,1,-0.186698,-0.126473,-0.148057,0.578762,0.524406,-0.838342,-1.115065
26065,-999.0,0,1,0,-0.209344,-0.058462,-0.166549,-0.519940,0.524406,-0.838342,-1.115065

In [53]:
train=final_df[final_df['likes']!=-999]
train.head()

,likes,GB,IN,US,views_std,dislikes_std,comment_count_std,category_id_median_likes_std,publish_year_std,publish_month_std,publish_day_std
0,2351.0,0,0,0,-0.022662,-0.077389,-0.085769,-0.554530,-1.274060,1.630641,-0.425818
1,3264.0,0,0,0,0.046318,-0.149251,-0.149138,-0.554530,0.524406,-0.591444,-0.885316
2,580.0,0,1,0,-0.217691,-0.124869,-0.172280,-0.554530,0.524406,-0.591444,1.182427
3,82773.0,1,0,0,0.076534,0.098735,0.307421,2.141912,0.524406,-0.838342,0.608054
4,3557.0,0,1,0,-0.196319,-0.150855,-0.165684,1.449957,0.524406,-0.097647,-0.655567

In [54]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(train.drop(labels=['likes'],axis=1),train['likes'],test_size=0.2,random_state=42)

In [64]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_log_error
import math
rf_reg=RandomForestRegressor()
rf_reg.fit(x_train,y_train)
y_pred=rf_reg.predict(x_test)
error=1000.0*(math.sqrt(mean_squared_log_error(y_test,y_pred)))
print('Root Mean Squared Log Error is:',error)

Root Mean Squared Log Error is: 841.0611694058458